name: Hello World
inputs:
  who_to_greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'

#runs:
#  using: 'docker'
#  image: 'Dockerfile'

runs:
  using: node16
  main: index.js
