name: Example
on: [push]

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Hello World
      uses: johannessarpola/rs-actions-helloworld@main
      with:
        who_to_greet: banana

